os: osx
osx_image: xcode9.3
language: objective-c

before_install:
  - rvm install ruby-2.3.1
  - gem install cocoapods
  - pod repo update
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true

script:
  - xcodebuild | xcpretty && exit ${PIPESTATUS[0]}
  - swiftlint

